<?xml version="1.0" encoding="utf-8"?><Database Name="DB_CMENU" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=DB_CMENU;Persist Security Info=True;User ID=sa" SettingsObjectName="cMenu.Test.Metaobjects.Properties.Settings" SettingsPropertyName="DB_CMENUConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.T_META_SEC" Member="T_META_SECs">
    <Type Name="T_META_SEC">
      <Column Name="F_USER_KEY" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_METAOBJECT_KEY" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_RIGHTS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="T_OBJ_T_META_SEC" Member="T_OBJ" ThisKey="F_METAOBJECT_KEY" OtherKey="F_OBJ_KEY" Type="T_OBJ" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_OBJ" Member="T_OBJs">
    <Type Name="T_OBJ">
      <Column Name="F_OBJ_KEY" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_OBJ_ID" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="F_OBJ_PARENT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="F_OBJ_CLASS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F_OBJ_SYSTEM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="F_OBJ_MOD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="F_OBJ_STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="T_OBJ_T_META_SEC" Member="T_META_SECs" ThisKey="F_OBJ_KEY" OtherKey="F_METAOBJECT_KEY" Type="T_META_SEC" />
    </Type>
  </Table>
</Database>