//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cMenu.Globalization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cMenu.Globalization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при взаимодействии с базой данных.
        /// </summary>
        internal static string ERROR_DB_INTERACTION {
            get {
                return ResourceManager.GetString("ERROR_DB_INTERACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно найти указанный рекламный модуль.
        /// </summary>
        internal static string ERROR_MSG_ADV_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_ADV_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан ключ идентификации устройства.
        /// </summary>
        internal static string ERROR_MSG_AUTH_TOKEN_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_AUTH_TOKEN_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры функции имеют неверный формат.
        /// </summary>
        internal static string ERROR_MSG_BAD_APP_PARAMS_JSON {
            get {
                return ResourceManager.GetString("ERROR_MSG_BAD_APP_PARAMS_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл конфигурации не найден или имеет неверный формат.
        /// </summary>
        internal static string ERROR_MSG_BAD_CONFIG {
            get {
                return ResourceManager.GetString("ERROR_MSG_BAD_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверная структура заказа.
        /// </summary>
        internal static string ERROR_MSG_BAD_ORDER {
            get {
                return ResourceManager.GetString("ERROR_MSG_BAD_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный тип форматирования результирующих данных.
        /// </summary>
        internal static string ERROR_MSG_BAD_RESULT_FORMAT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_MSG_BAD_RESULT_FORMAT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вызываемая функция в данный момент недоступна или отключена.
        /// </summary>
        internal static string ERROR_MSG_BAD_SERVER_APP_DISABLED {
            get {
                return ResourceManager.GetString("ERROR_MSG_BAD_SERVER_APP_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный идентификатор функции.
        /// </summary>
        internal static string ERROR_MSG_BAD_SERVER_APP_ID {
            get {
                return ResourceManager.GetString("ERROR_MSG_BAD_SERVER_APP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренняя ошибка функции.
        /// </summary>
        internal static string ERROR_MSG_BAD_SERVER_APP_INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("ERROR_MSG_BAD_SERVER_APP_INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функция с указанными идентификатором не найдена.
        /// </summary>
        internal static string ERROR_MSG_BAD_SERVER_APP_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_BAD_SERVER_APP_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл конфигурации не найден или имеет неверный формат.
        /// </summary>
        internal static string ERROR_MSG_BAD_SERVER_CONFIG_FILE {
            get {
                return ResourceManager.GetString("ERROR_MSG_BAD_SERVER_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно найти указанную категорию.
        /// </summary>
        internal static string ERROR_MSG_CATEGORY_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_CATEGORY_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка коммуникации. Возможно, на сервере произошел непредвиденный сбой.
        /// </summary>
        internal static string ERROR_MSG_COMMUNICATION_CLIENT_ERROR {
            get {
                return ResourceManager.GetString("ERROR_MSG_COMMUNICATION_CLIENT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В запросе не указана длительность сессии.
        /// </summary>
        internal static string ERROR_MSG_DEADLINE_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_DEADLINE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данному устройству отказано в авторизации, так как оно, возможно, находится в черном списке.
        /// </summary>
        internal static string ERROR_MSG_DEVICE_BANNED {
            get {
                return ResourceManager.GetString("ERROR_MSG_DEVICE_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В запросе не указан идентификатор устройства.
        /// </summary>
        internal static string ERROR_MSG_DEVICE_ID_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_MSG_DEVICE_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройство с заданным идентификатором не найдено.
        /// </summary>
        internal static string ERROR_MSG_DEVICE_ID_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_DEVICE_ID_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В запросе не указан MAC адрес устройства.
        /// </summary>
        internal static string ERROR_MSG_DEVICE_MAC_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_MSG_DEVICE_MAC_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В запросе не указано наименование устройства.
        /// </summary>
        internal static string ERROR_MSG_DEVICE_NAME_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_MSG_DEVICE_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В запросе не указан тип регистриемого устройства..
        /// </summary>
        internal static string ERROR_MSG_DEVICE_TYPE_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_DEVICE_TYPE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанная функция не найдена на сервере.
        /// </summary>
        internal static string ERROR_MSG_FUNCTION_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_FUNCTION_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан заказ.
        /// </summary>
        internal static string ERROR_MSG_INPUT_ORDER_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_INPUT_ORDER_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В запросе не указана ключевая информация: идентификатор или ключ объекта.
        /// </summary>
        internal static string ERROR_MSG_KEY_ID_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_KEY_ID_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В запросе не указано имя пользователя.
        /// </summary>
        internal static string ERROR_MSG_LOGIN_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_LOGIN_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно найти указанный медиа ресурс.
        /// </summary>
        internal static string ERROR_MSG_MEDIA_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_MEDIA_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В базе не найдено ни одного меню.
        /// </summary>
        internal static string ERROR_MSG_NO_MENUS {
            get {
                return ResourceManager.GetString("ERROR_MSG_NO_MENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В базне не найдено ни одного активного меню.
        /// </summary>
        internal static string ERROR_MSG_NO_PRIMARY_MENU {
            get {
                return ResourceManager.GetString("ERROR_MSG_NO_PRIMARY_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно найти указанный заказ.
        /// </summary>
        internal static string ERROR_MSG_ORDER_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_ORDER_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В запросе не указан пароль пользователя.
        /// </summary>
        internal static string ERROR_MSG_PASSWORD_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_PASSWORD_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка входа.
        /// </summary>
        internal static string ERROR_MSG_SERVER_ENDPOINT {
            get {
                return ResourceManager.GetString("ERROR_MSG_SERVER_ENDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация сервера.
        /// </summary>
        internal static string ERROR_MSG_SERVER_INIT {
            get {
                return ResourceManager.GetString("ERROR_MSG_SERVER_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск сервера.
        /// </summary>
        internal static string ERROR_MSG_SERVER_START {
            get {
                return ResourceManager.GetString("ERROR_MSG_SERVER_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановка сервера.
        /// </summary>
        internal static string ERROR_MSG_SERVER_STOP {
            get {
                return ResourceManager.GetString("ERROR_MSG_SERVER_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер не отвечает на запросы.
        /// </summary>
        internal static string ERROR_MSG_SERVICE_UNAVAILABLE {
            get {
                return ResourceManager.GetString("ERROR_MSG_SERVICE_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сессия истекла.
        /// </summary>
        internal static string ERROR_MSG_SESSION_EXPIRED {
            get {
                return ResourceManager.GetString("ERROR_MSG_SESSION_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сессия с указанным ключом устройсва не найдена.
        /// </summary>
        internal static string ERROR_MSG_SESSION_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_SESSION_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление успешно отображено.
        /// </summary>
        internal static string ERROR_MSG_SHOW_NOTIFICATION {
            get {
                return ResourceManager.GetString("ERROR_MSG_SHOW_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция выполнена успешно.
        /// </summary>
        internal static string ERROR_MSG_SUCCESS {
            get {
                return ResourceManager.GetString("ERROR_MSG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отобразить уведомление на конечном компьютере.
        /// </summary>
        internal static string ERROR_MSG_UNABLE_SHOW_NOTIFICATION {
            get {
                return ResourceManager.GetString("ERROR_MSG_UNABLE_SHOW_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь аутентифицирован.
        /// </summary>
        internal static string ERROR_MSG_USER_AUTHENTICATED {
            get {
                return ResourceManager.GetString("ERROR_MSG_USER_AUTHENTICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователю, соответствуюшему указанной сессии, запрещен вход в систему.
        /// </summary>
        internal static string ERROR_MSG_USER_BANNED {
            get {
                return ResourceManager.GetString("ERROR_MSG_USER_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователю, соответствуюшему указанной сессии, не разрешен вход в систему.
        /// </summary>
        internal static string ERROR_MSG_USER_DISABLED {
            get {
                return ResourceManager.GetString("ERROR_MSG_USER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не имеет прав доступа к выбранному объекту.
        /// </summary>
        internal static string ERROR_MSG_USER_HASNT_ACCESS_TO_OBJECT {
            get {
                return ResourceManager.GetString("ERROR_MSG_USER_HASNT_ACCESS_TO_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с заданными логином и паролем не найдены.
        /// </summary>
        internal static string ERROR_MSG_USER_LOGIN_PASS_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_USER_LOGIN_PASS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У пользователя нет прав на привязку устройств.
        /// </summary>
        internal static string ERROR_MSG_USER_NOT_ALLOWED_BIND_DEVICES {
            get {
                return ResourceManager.GetString("ERROR_MSG_USER_NOT_ALLOWED_BIND_DEVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно установить связь между объектами.
        /// </summary>
        internal static string ERROR_MSG_USER_NOT_ALLOWED_CREATE_LINKS {
            get {
                return ResourceManager.GetString("ERROR_MSG_USER_NOT_ALLOWED_CREATE_LINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось раздать права на объект пользователю или группе.
        /// </summary>
        internal static string ERROR_MSG_USER_NOT_ALLOWED_CREATE_SEC_RECORD {
            get {
                return ResourceManager.GetString("ERROR_MSG_USER_NOT_ALLOWED_CREATE_SEC_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У пользователя нет прав на создание сессий.
        /// </summary>
        internal static string ERROR_MSG_USER_NOT_ALLOWED_CREATE_SESSIONS {
            get {
                return ResourceManager.GetString("ERROR_MSG_USER_NOT_ALLOWED_CREATE_SESSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден пользователь, соответствующий указанной сессии.
        /// </summary>
        internal static string ERROR_MSG_USER_SESSION_NULL {
            get {
                return ResourceManager.GetString("ERROR_MSG_USER_SESSION_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не имеет права на редактирование списка заказов.
        /// </summary>
        internal static string ERROR_MSG_USER_UNABLE_TO_EDIT_ORDERS {
            get {
                return ResourceManager.GetString("ERROR_MSG_USER_UNABLE_TO_EDIT_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не имеет права на просмотр списка объектов.
        /// </summary>
        internal static string ERROR_MSG_USER_UNABLE_TO_VIEW_OBJECT {
            get {
                return ResourceManager.GetString("ERROR_MSG_USER_UNABLE_TO_VIEW_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не имеет права на просмотр списка заказов.
        /// </summary>
        internal static string ERROR_MSG_USER_UNABLE_TO_VIEW_ORDERS {
            get {
                return ResourceManager.GetString("ERROR_MSG_USER_UNABLE_TO_VIEW_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указаны неверные данные для аутентификации.
        /// </summary>
        internal static string ERROR_MT_AUTH_DATA_NULL {
            get {
                return ResourceManager.GetString("ERROR_MT_AUTH_DATA_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите закрыть текущее соединение?.
        /// </summary>
        internal static string ERROR_MT_CLOSE_CONNECTION {
            get {
                return ResourceManager.GetString("ERROR_MT_CLOSE_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано имя БД.
        /// </summary>
        internal static string ERROR_MT_DB_NAME_NULL {
            get {
                return ResourceManager.GetString("ERROR_MT_DB_NAME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан пароль пользователя сервера БД.
        /// </summary>
        internal static string ERROR_MT_DB_PASS_NULL {
            get {
                return ResourceManager.GetString("ERROR_MT_DB_PASS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано имя пользователя сервера БД.
        /// </summary>
        internal static string ERROR_MT_DB_USER_NULL {
            get {
                return ResourceManager.GetString("ERROR_MT_DB_USER_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите удалить выделенный элемент?.
        /// </summary>
        internal static string ERROR_MT_DELETE_ITEM {
            get {
                return ResourceManager.GetString("ERROR_MT_DELETE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите удалить элемент.
        /// </summary>
        internal static string ERROR_MT_DELETE_ITEM_2 {
            get {
                return ResourceManager.GetString("ERROR_MT_DELETE_ITEM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код языка имеет целочисленный формат.
        /// </summary>
        internal static string ERROR_MT_LANGUAGE_CODE_BAD {
            get {
                return ResourceManager.GetString("ERROR_MT_LANGUAGE_CODE_BAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан код языка по умолчанию.
        /// </summary>
        internal static string ERROR_MT_LANGUAGE_CODE_NULL {
            get {
                return ResourceManager.GetString("ERROR_MT_LANGUAGE_CODE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано имя пользователя.
        /// </summary>
        internal static string ERROR_MT_LOGIN_NULL {
            get {
                return ResourceManager.GetString("ERROR_MT_LOGIN_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано имя.
        /// </summary>
        internal static string ERROR_MT_NAME_NULL {
            get {
                return ResourceManager.GetString("ERROR_MT_NAME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан пароль.
        /// </summary>
        internal static string ERROR_MT_PASS_NULL {
            get {
                return ResourceManager.GetString("ERROR_MT_PASS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан адрес сервера БД.
        /// </summary>
        internal static string ERROR_MT_SERVER_ADDR_NULL {
            get {
                return ResourceManager.GetString("ERROR_MT_SERVER_ADDR_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно связаться с сервером. Возможно, неверно указана информация о пользователе сервера БД или сервер БД остановлен.
        /// </summary>
        internal static string ERROR_MT_SERVER_NOT_RESPOND {
            get {
                return ResourceManager.GetString("ERROR_MT_SERVER_NOT_RESPOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с указанным логином не имеет права на просмотр репозитория безопасности.
        /// </summary>
        internal static string ERROR_MT_USER_NOT_ENOUGH_RIGHTS_SEC_REPO {
            get {
                return ResourceManager.GetString("ERROR_MT_USER_NOT_ENOUGH_RIGHTS_SEC_REPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вызов официанта.
        /// </summary>
        internal static string MSG_CALL_OFICIANT {
            get {
                return ResourceManager.GetString("MSG_CALL_OFICIANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копия.
        /// </summary>
        internal static string MSG_COPY {
            get {
                return ResourceManager.GetString("MSG_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя устройства.
        /// </summary>
        internal static string MSG_DEVICE_NAME {
            get {
                return ResourceManager.GetString("MSG_DEVICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ.
        /// </summary>
        internal static string MSG_MAKE_ORDER {
            get {
                return ResourceManager.GetString("MSG_MAKE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ярлык для.
        /// </summary>
        internal static string MSG_SHORTCUT {
            get {
                return ResourceManager.GetString("MSG_SHORTCUT", resourceCulture);
            }
        }
    }
}
